chore: Fix the graceful shutdown and make sure that we always log to stderr

diff --git a/bin/varnish-reload-vcl b/bin/varnish-reload-vcl
--- a/bin/varnish-reload-vcl
+++ b/bin/varnish-reload-vcl
@@ -7,28 +7,28 @@ ADMIN=localhost:$VARNISH_ADMIN_PORT
 NAME="varnish_$(date +%s)"
 
 function error () {
-  >&2 echo $1
+  echo $1
   exit 1
 }
 
-varnishadm() {
+varnishadm () {
   if ! OUTPUT=$(command varnishadm -T $ADMIN -S $VARNISH_ADMIN_SECRET_FILE -- "$@" 2>&1)
   then
-    >&2 echo "Command: varnishadm -T $ADMIN -S $VARNISH_ADMIN_SECRET_FILE -- $*"
-    >&2 echo
-    >&2 echo "$OUTPUT"
-    >&2 echo
+    echo "Command: varnishadm -T $ADMIN -S $VARNISH_ADMIN_SECRET_FILE -- $*"
+    echo
+    echo "$OUTPUT"
+    echo
     return 1
-  fi >&2
+  fi
   echo "$OUTPUT"
 }
 
->&2 varnishadm vcl.load $NAME $FILE || error "Failed to vcl.load $FILE."
->&2 varnishadm vcl.use $NAME || error "Failed to vcl.use $FILE."
+varnishadm vcl.load $NAME $FILE || error "Failed to vcl.load $FILE."
+varnishadm vcl.use $NAME || error "Failed to vcl.use $FILE."
 sleep 10
 
 INACTIVE_VCLS=$(varnishadm vcl.list | awk '/(auto|cold)\/cold/ {print $4}') || error "Failed to get the vcl list."
 for vclname in $INACTIVE_VCLS; do
-  >&2 echo "Call varnishadm vcl.discard $vclname"
+  echo "Call varnishadm vcl.discard $vclname"
   varnishadm vcl.discard $vclname 1>/dev/null || error "Failed to vcl.discard $vclname."
 done;
