chore: Migrate the entrypoint to node to properly handle shutdown signals and error logging

diff --git a/bin/varnish-reload-vcl b/bin/varnish-reload-vcl
--- a/bin/varnish-reload-vcl
+++ b/bin/varnish-reload-vcl
@@ -1,7 +1,6 @@
 #!/bin/bash
 set -e
 trap "exit 0" SIGINT SIGTERM
-exec 1> >(awk '{print strftime("%Y-%m-%dT%H:%M:%SZ",systime()) " [varnish-reload-vcl]: " $0;}') 2>&1
 
 FILE=$VARNISH_CONFIG
 ADMIN=localhost:$VARNISH_ADMIN_PORT
@@ -26,10 +25,9 @@ varnishadm () {
 
 varnishadm vcl.load $NAME $FILE || error "Failed to vcl.load $FILE."
 varnishadm vcl.use $NAME || error "Failed to vcl.use $FILE."
-sleep 10
 
-INACTIVE_VCLS=$(varnishadm vcl.list | awk '/(auto|cold)\/cold/ {print $4}') || error "Failed to get the vcl list."
+INACTIVE_VCLS=$(varnishadm vcl.list | awk '/^available/ {print $5}') || error "Failed to get the vcl list."
 for vclname in $INACTIVE_VCLS; do
   echo "Call varnishadm vcl.discard $vclname"
-  varnishadm vcl.discard $vclname 1>/dev/null || error "Failed to vcl.discard $vclname."
+  varnishadm vcl.discard $vclname 1>/dev/null || echo "Failed to vcl.discard $vclname."
 done;
